### ISSUE TITLE
Request feature: auto detect color is darkness

### ISSUE THREAD

**Issue by webserveis** [jisungbin/SystemUiController#1]
It might be useful to detect how dark a color is to set icons to dark or light mode.

In Kotlin using extension function on Int type and with a darkness threshold parameter it can look like the following:

```kotlin
/**
 * Determines if this color is dark.
 * @param threshold - min darkness value; the higher the value, the darker the color;
 * float value between 0.0 and 1.0.
 */
fun Int.isColorDark(@FloatRange(from = 0.0, to = 1.0) threshold: Float = 0.9f): Boolean {
    val darkness = 1 - (Color.red(this) * 0.299 + Color.green(this) * 0.587 + Color.blue(this) * 0.114) / 255
    return darkness >= threshold
}
```

**Comment by jisungbin** [comment]
Hi! Thanks for your contribution. `1.0.1` is released as your contribution has just been merged(https://github.com/jisungbin/SystemUiController/pull/2). Check out the new version. thanks!
